-- Congelados JEMY: reemplaza TODOS los productos por la lista de precios del 17/09/2026.
-- 226 productos: 190 visibles en la tienda y 36 ocultos (precio $0 en la lista).
-- Todos arrancan con stock 0: cargá el stock desde el panel.
begin;
delete from productos;
insert into productos (categoria, nombre, precio, emoji, activo) values
  ('Papas', 'McCain Noisette x bolsa', 21591, '🍟', true),
  ('Papas', 'McCain Noisette x caja (10 kg)', 86365, '🍟', true),
  ('Papas', 'McCain Smiles x bolsa', 14031, '🍟', true),
  ('Papas', 'McCain Smiles x caja (9 kg)', 80178, '🍟', true),
  ('Papas', 'McCain Aros de cebolla x bolsa', 13636, '🍟', true),
  ('Papas', 'McCain Aros de cebolla x caja (10 kg)', 136364, '🍟', true),
  ('Papas', 'McCain Corte tradicional x bolsa', 12679, '🍟', true),
  ('Papas', 'McCain Corte tradicional x caja (15 kg)', 72450, '🍟', true),
  ('Papas', 'McCain Crinkle x bolsa', 17663, '🍟', true),
  ('Papas', 'McCain Crinkle x caja (12,5 kg)', 84111, '🍟', true),
  ('Papas', 'McCain Sure Crisp extra crocante x bolsa', 19515, '🍟', true),
  ('Papas', 'McCain Sure Crisp extra crocante x caja (15 kg)', 111516, '🍟', true),
  ('Papas', 'McCain Sure Crisp extra crocante corte fino x bolsa', 27348, '🍟', true),
  ('Papas', 'McCain Sure Crisp extra crocante corte fino x caja (18 kg)', 156274, '🍟', true),
  ('Papas', 'McCain Bastón de boniato 9x9 x bolsa', 27348, '🍟', true),
  ('Papas', 'McCain Bastón de boniato 9x9 x caja (15 kg)', 156274, '🍟', true),
  ('Papas', 'McCain Guacamole x 450 grs.', 14460, '🥑', true),
  ('Papas', 'Simplot Aros de cebolla x caja (10 kg)', 0, '🍟', false),
  ('Papas', 'Simplot Tradicional x bolsa', 10908, '🍟', true),
  ('Papas', 'Simplot Tradicional x caja (14 kg)', 62330, '🍟', true),
  ('Papas', 'Simplot Corte fino x bolsa', 14289, '🍟', true),
  ('Papas', 'Simplot Corte fino x caja (18 kg)', 81650, '🍟', true),
  ('Papas', 'Simplot Crunch x bolsa', 13474, '🍟', true),
  ('Papas', 'Simplot Crunch x caja (15 kg)', 76993, '🍟', true),
  ('Papas', 'Simplot Cool Mind corte fino x bolsa', 8830, '🍟', true),
  ('Papas', 'Simplot Cool Mind corte fino x caja (18 kg)', 67275, '🍟', true),
  ('Papas', 'Simplot Cool Mind tradicional x caja (15 kg)', 0, '🍟', false),
  ('Papas', 'Simplot Cool Mind Cristal x caja (14 kg)', 0, '🍟', false),
  ('Papas', 'Finca Balcarce Tradicional x caja (10 kg)', 0, '🍟', false),
  ('Papas', 'Lamb Weston Tradicional 9 mm x bolsa', 7511, '🍟', true),
  ('Papas', 'Lamb Weston Tradicional 9 mm x caja (15 kg)', 57230, '🍟', true),
  ('Papas', 'Lamb Weston Stealth Fries x caja (15 kg)', 61791, '🍟', true),
  ('Papas', 'Lamb Weston Ziggy Fries x bolsa', 16482, '🍟', true),
  ('Papas', 'Lamb Weston Ziggy Fries x caja (10 kg)', 62790, '🍟', true),
  ('Papas', 'Lamb Weston Butler x bolsa', 8329, '🍟', true),
  ('Papas', 'Lamb Weston Butler x caja (15 kg)', 47594, '🍟', true),
  ('Rebozados de pollo', 'Ártico Medallones de pollo x caja (6 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Ártico Patitas/Formitas x caja (6 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Ártico Medallón de pollo c/ JyQ x caja (6 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Ártico Medallón de pollo c/ espinaca x caja (6 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Ártico Crujiente de pollo x caja (6 kg)', 68176, '🍗', true),
  ('Rebozados de pollo', 'Ártico Barritas de muzzarella x bolsa', 23501, '🍗', true),
  ('Rebozados de pollo', 'Ártico Barritas de muzzarella x caja (6 kg)', 70504, '🍗', true),
  ('Rebozados de pollo', 'Ártico Nuggets crocante x bolsa', 21220, '🍗', true),
  ('Rebozados de pollo', 'Ártico Nuggets crocante x caja (6 kg)', 63660, '🍗', true),
  ('Rebozados de pollo', 'Granja Tres Arroyos Crispy de pollo x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Pochoclo de pollo x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Bocaditos de pollo x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Medallones de pollo x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Medallones de pollo c/ JyQ x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Bastones de queso x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Ricosaurios x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Supremas de pollo horneadas x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Pechuguitas de pollo rebozadas x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Granja Tres Arroyos Nuggets x caja (5 kg)', 0, '🍗', false),
  ('Rebozados de pollo', 'Unión Ganadera Nugget crocante x 300 grs. x bolsa', 3469, '🍗', true),
  ('Rebozados de pollo', 'Unión Ganadera Nugget crocante x 300 grs. x caja (20 u.)', 66068, '🍗', true),
  ('Rebozados de pollo', 'Unión Ganadera Nugget crocante x 1 kg x bolsa', 11598, '🍗', true),
  ('Rebozados de pollo', 'Unión Ganadera Nugget crocante x 1 kg x caja (10 u.)', 110458, '🍗', true),
  ('Rebozados de pollo', 'Grangys Nuggets de pollo x bolsa', 8927, '🍗', true),
  ('Rebozados de pollo', 'Grangys Nuggets de pollo x caja (6 kg)', 51012, '🍗', true),
  ('Rebozados de pollo', 'Grangys Nuggets tempura x bolsa', 9992, '🍗', true),
  ('Rebozados de pollo', 'Grangys Nuggets tempura x caja', 57096, '🍗', true),
  ('Rebozados de pollo', 'Grangys Dinos de pollo x bolsa', 7391, '🍗', true),
  ('Rebozados de pollo', 'Grangys Dinos de pollo x caja (6 kg)', 42237, '🍗', true),
  ('Rebozados de pollo', 'Grangys Patitas de pollo rebozadas x caja (5 kg)', 32877, '🍗', true),
  ('Rebozados de pollo', 'Grangys Cañoncitos de muzzarella x bolsa', 16342, '🍗', true),
  ('Rebozados de pollo', 'Grangys Cañoncitos de muzzarella x caja (6 kg)', 77817, '🍗', true),
  ('Rebozados de pollo', 'Sadia Nuggets x bolsa', 26692, '🍗', true),
  ('Rebozados de pollo', 'Sadia Nuggets x caja (6 kg)', 50842, '🍗', true),
  ('Tortillas', 'Ueno Tortilla de papa y cebolla x bolsa', 4968, '🥔', true),
  ('Tortillas', 'Ueno Tortilla de papa y cebolla x caja (10 u.)', 47311, '🥔', true),
  ('Tequeños', 'Tequeños Masas Planet x 12 unid.', 6442, '🧀', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 40x110 grs.', 99424, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 36x120 grs.', 0, '🍔', false),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 20x140 grs.', 58101, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 60x83 grs.', 112008, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 72x69 grs.', 113094, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 20x83 grs.', 37750, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 12x83 grs.', 23302, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 8x120 grs.', 24201, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 2x120 grs.', 0, '🍔', false),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 4x83 grs.', 7768, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Unión Ganadera 4x69 grs.', 6268, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Victoria 40x110 grs.', 73083, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Victoria 60x83 grs.', 80052, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Tuki 4x80 grs.', 6670, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Tuki 40x110 grs.', 62675, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Tuki 60x80 grs.', 69311, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Paty 40x110 grs. Quick Food', 0, '🍔', false),
  ('Hamburguesas', 'Hamburguesas Paty 40x125 grs.', 77389, '🍔', true),
  ('Hamburguesas', 'Hamburguesas Paty 60x80 grs.', 67965, '🍔', true),
  ('Hamburguesas', 'Hamburguesas veganas NotCo x 31 unid.', 63720, '🌱', true),
  ('Medallones', 'Medallones Unión Ganadera 36x83 grs.', 66631, '🥩', true),
  ('Medallones', 'Medallones Unión Ganadera 40x110 grs.', 93852, '🥩', true),
  ('Medallones', 'Medallones Unión Ganadera 60x83 grs.', 104156, '🥩', true),
  ('Medallones', 'Medallones Unión Ganadera 72x69 grs.', 105317, '🥩', true),
  ('Medallones', 'Medallones Unión Ganadera 72x55 grs.', 81092, '🥩', true),
  ('Medallones', 'Medallones Victoria 40x110 grs.', 32269, '🥩', true),
  ('Medallones', 'Medallones Victoria 60x69 grs.', 34891, '🥩', true),
  ('Salchichas', 'Salchichas alemanas Unión Ganadera 5 x 12 unid. x paquete', 6429, '🌭', true),
  ('Salchichas', 'Salchichas alemanas Unión Ganadera 5 x 12 unid. x caja (12 paq.)', 73474, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera cortas 20 x 6 unid. x paquete', 1830, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera cortas 20 x 6 unid. x caja (6 paq.)', 34857, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera largas 9 x 12 unid. x paquete', 8141, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera largas 9 x 12 unid. x caja (9 paq.)', 69782, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera largas 18 x 6 unid. x paquete', 4128, '🌭', true),
  ('Salchichas', 'Salchichas Unión Ganadera largas 18 x 6 unid. x caja (18 paq.)', 70771, '🌭', true),
  ('Salchichas', 'Salchichas Tuki 18 paq. x 6 unid. x paquete', 2347, '🌭', true),
  ('Salchichas', 'Salchichas Tuki 18 paq. x 6 unid. x caja (18 paq.)', 40227, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra largas 6 x 18 unid. x paquete', 7301, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra largas 6 x 18 unid. x caja (6 paq.)', 41722, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra cortas 20 x 6 unid. x paquete', 1264, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra cortas 20 x 6 unid. x caja', 24070, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra largas 9 x 12 unid. x paquete', 6534, '🌭', true),
  ('Salchichas', 'Salchichas Chacra Nuestra largas 9 x 12 unid. x caja', 56005, '🌭', true),
  ('Panificados', 'Pan de hamburguesa clásico x 4 - Fargo', 1984, '🍞', true),
  ('Panificados', 'Pan de hamburguesa grande c/ sésamo x 20 - Fargo', 14375, '🍞', true),
  ('Panificados', 'Pan de superpancho x 6 - Fargo', 3324, '🍞', true),
  ('Panificados', 'Parmesano, semillas, papas x 15 - De Masa Madre', 11124, '🍞', true),
  ('Panificados', 'Mini de queso x 24 - De Masa Madre', 11742, '🍞', true),
  ('Panificados', 'Lunáticas x 12 - De Masa Madre', 24102, '🍞', true),
  ('Panificados', 'Pan de hot dog x 20 - De Masa Madre', 16686, '🍞', true),
  ('Panificados', 'Pan de lomo (25 cm) x 10 - De Masa Madre', 10918, '🍞', true),
  ('Panificados', 'Pan de lomito (17 cm) x 15 - De Masa Madre', 12669, '🍞', true),
  ('Panificados', 'Pan Bari (25 cm) x 10 - De Masa Madre', 9270, '🍞', true),
  ('Panificados', 'Pan de hamburguesa clásico x 4 - Trigo Premium', 0, '🍞', false),
  ('Panificados', 'Pan de superpancho Panigazzi x 4 - Trigo Premium', 0, '🍞', false),
  ('Panificados', 'Pan de superpancho x 6 - Trigo Premium', 1666, '🍞', true),
  ('Panificados', 'Pan de hamburguesa clásico x 4 - Ave Fénix', 1391, '🍞', true),
  ('Panificados', 'Pan de hamburguesa gigante x 4 - Ave Fénix', 1612, '🍞', true),
  ('Panificados', 'Pan de superpancho x 6 - Ave Fénix', 1612, '🍞', true),
  ('Aderezos', 'Benidorm Mayonesa pomo 500 cc', 1714, '🥫', true),
  ('Aderezos', 'Benidorm Salsa golf pomo 500 cc', 1824, '🥫', true),
  ('Aderezos', 'Benidorm Mostaza pomo 500 cc', 1598, '🥫', true),
  ('Aderezos', 'Benidorm Ketchup pomo 500 cc', 2308, '🥫', true),
  ('Aderezos', 'Benidorm Cheddar pomo 500 cc', 2748, '🥫', true),
  ('Aderezos', 'Benidorm Parmesano pomo 500 cc', 2581, '🥫', true),
  ('Aderezos', 'Benidorm Roquefort pomo 500 cc', 2742, '🥫', true),
  ('Aderezos', 'Benidorm Pasta de aceitunas pomo 500 cc', 1824, '🥫', true),
  ('Aderezos', 'Benidorm Salsa tartarina pomo 500 cc', 1822, '🥫', true),
  ('Aderezos', 'Benidorm Fugazzeta pomo 500 cc', 2704, '🥫', true),
  ('Aderezos', 'Benidorm Chimichurri pomo 500 cc', 1927, '🥫', true),
  ('Aderezos', 'Benidorm Barbacoa pomo 500 cc', 2538, '🥫', true),
  ('Aderezos', 'Benidorm Salame pomo 500 cc', 2383, '🥫', true),
  ('Aderezos', 'Benidorm Salsa ají pomo 500 cc', 2653, '🥫', true),
  ('Aderezos', 'Benidorm Mayonesa individual (200 x 8 grs.)', 8629, '🥫', true),
  ('Aderezos', 'Benidorm Ketchup individual (200 x 8 grs.)', 12360, '🥫', true),
  ('Aderezos', 'Benidorm Mostaza individual (200 x 8 grs.)', 8053, '🥫', true),
  ('Aderezos', 'Benidorm Mayonesa x 3 kg', 5850, '🥫', true),
  ('Aderezos', 'Benidorm Ketchup x 3 kg', 10118, '🥫', true),
  ('Aderezos', 'Benidorm Mostaza x 3 kg', 5302, '🥫', true),
  ('Aderezos', 'Hellmann''s Mayonesa individual', 17784, '🥫', true),
  ('Aderezos', 'Hellmann''s Ketchup individual', 16572, '🥫', true),
  ('Aderezos', 'Hellmann''s Mostaza individual', 14544, '🥫', true),
  ('Aderezos', 'Hellmann''s Salsa golf individual', 0, '🥫', false),
  ('Aderezos', 'Mayonesa Hellmann''s x 3 kg', 14424, '🥫', true),
  ('Aderezos', 'Ketchup Hellmann''s x 3 kg', 15540, '🥫', true),
  ('Aderezos', 'Savora x 3 kg', 12740, '🥫', true),
  ('Aderezos', 'Salsa golf Hellmann''s x 3 kg', 0, '🥫', false),
  ('Aderezos', 'Barbacoa Hellmann''s x 3 kg', 16475, '🥫', true),
  ('Aderezos', 'Barbacoa Tau x 3 kg', 0, '🥫', false),
  ('Cheddar', 'Cheddar Milkaut fetas x 192 unid.', 43355, '🧀', true),
  ('Cheddar', 'Cheddar Milkaut caja x 4 barras de 192 fetas', 170404, '🧀', true),
  ('Cheddar', 'Cheddar Milkaut pouch 3,5 kg', 32925, '🧀', true),
  ('Cheddar', 'Cheddar Tonadita fetas americano x 140 fetas', 25141, '🧀', true),
  ('Cheddar', 'Cheddar Tonadita fetas (168 fetas)', 148224, '🧀', true),
  ('Cheddar', 'Cheddar Tonadita pouch', 25421, '🧀', true),
  ('Sazonadores', 'Sazonador sabor queso Muzz x 1 kg', 43700, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor queso Muzz x 1 kg', 39100, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor queso Muzz x 500 grs.', 21965, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor ahumado Muzz x 1 kg', 39100, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor ahumado Muzz x 500 grs.', 21965, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor parmesano Muzz x 1 kg', 39100, '🧂', true),
  ('Sazonadores', 'Sazonador para papas sabor parmesano Muzz x 500 grs.', 21965, '🧂', true),
  ('Salsas', 'Salsa Big Burger MC x 500 grs.', 0, '🥫', false),
  ('Salsas', 'Salsa Parrinesa MC x 1 kg x unidad', 5276, '🥫', true),
  ('Salsas', 'Salsa Parrinesa MC x 1 kg x caja (20 u.)', 50247, '🥫', true),
  ('Salsas', 'Salsa Chiminesa MC x 500 grs.', 0, '🥫', false),
  ('Salsas', 'Salsa Tasty artesanal Kinga x 1 lt.', 8050, '🥫', true),
  ('Salsas', 'Salsa Stacker artesanal Kinga x 1 lt.', 8050, '🥫', true),
  ('Salsas', 'Salsa Spicy artesanal Kinga x 1 lt.', 8280, '🥫', true),
  ('Salsas', 'Salsa Hot artesanal Kinga x 1 lt.', 8280, '🥫', true),
  ('Salsas', 'Salsa Mayo Chimi artesanal Kinga x 1 lt.', 7820, '🥫', true),
  ('Salsas', 'Salsa King Mustang artesanal Kinga x 1 lt.', 8165, '🥫', true),
  ('Salsas', 'Salsa Cuarto artesanal Kinga x 1 lt.', 8625, '🥫', true),
  ('Salsas', 'Salsa Alioli artesanal Kinga x 1 lt.', 7475, '🥫', true),
  ('Salsas', 'Salsa Big artesanal Kinga x 1 lt.', 8050, '🥫', true),
  ('Conservas', 'Pepinos agridulces Kinga x 750 grs.', 7935, '🥒', true),
  ('Conservas', 'Spicy Relish Kinga x 1 kg', 10465, '🥒', true),
  ('Conservas', 'Sweet Relish Kinga x 1 kg', 10178, '🥒', true),
  ('Aceites', 'Aceite alto oleico Seda (bag x 10 lts.)', 47219, '🛢️', true),
  ('Aceites', 'Aceite medio oleico Seda (bag x 10 lts.)', 44264, '🛢️', true),
  ('Aceites', 'Aceite alto oleico Areco x 20 lts.', 82225, '🛢️', true),
  ('Aceites', 'Aceite alto oleico Areco x 5 lts.', 21093, '🛢️', true),
  ('Fiambres', 'Jamón mini Luvianka x kg', 12800, '🥓', true),
  ('Fiambres', 'Jamón bombón cocido Luvianka x kg', 14720, '🥓', true),
  ('Fiambres', 'Pata de cerdo Barril x kg', 0, '🥓', false),
  ('Fiambres', 'Paleta Luvianka x kg', 7406, '🥓', true),
  ('Fiambres', 'Panceta ahumada Luvianka x kg', 15218, '🥓', true),
  ('Fiambres', 'Panceta ternizada Luvianka x kg', 8769, '🥓', true),
  ('Fiambres', 'Lomo a las finas hierbas Luvianka x kg', 0, '🥓', false),
  ('Fiambres', 'Panceta ahumada Scudetto x kg', 10961, '🥓', true),
  ('Quesos', 'Queso Dambo x kg', 8573, '🧀', true),
  ('Quesos', 'Queso Tybo x kg', 0, '🧀', false),
  ('Quesos', 'Provoleta Santa Rosa x kg', 10812, '🧀', true),
  ('Quesos', 'Provoleta Milkaut x kg', 10787, '🧀', true),
  ('Quesos', 'Provoleta Nonna Pia x kg', 17365, '🧀', true),
  ('Quesos', 'Queso azul o roquefort x kg', 0, '🧀', false),
  ('Quesos', 'Mozzarella Tarantela x kg', 0, '🧀', false),
  ('Varios', 'Aceitunas x balde', 0, '🛒', false),
  ('Varios', 'Pepino corte americano x balde 8 kg', 0, '🛒', false),
  ('Varios', 'Papas pay Sol de Junio x 900 grs.', 9312, '🛒', true),
  ('Papelera', 'Caja para burger', 243, '📦', true),
  ('Papelera', 'Caja para lomo', 0, '📦', false),
  ('Papelera', 'Caja para pizza', 224, '📦', true),
  ('Papelera', 'Guantes de nitrilo x 100 unid. (S, M, L, XL)', 9475, '📦', true),
  ('Papelera', 'Papel térmico para hamburguesa', 22750, '📦', true),
  ('Papelera', 'Papel parafinado x kg', 14213, '📦', true),
  ('Condimentos', 'Sal individual', 8050, '🌿', true),
  ('Condimentos', 'Provenzal x 1 kg', 9375, '🌿', true),
  ('Condimentos', 'Condimento para pizza x 1 kg', 11875, '🌿', true),
  ('Condimentos', 'Pimentón dulce x 1 kg', 12250, '🌿', true),
  ('Condimentos', 'Pimienta blanca x 1 kg', 30000, '🌿', true),
  ('Condimentos', 'Orégano x 1 kg', 9500, '🌿', true),
  ('Condimentos', 'Ají molido x 1 kg', 12000, '🌿', true);
commit;
