-- =====================================================================
--  CONGELADOS JEMY — Base de datos (Supabase)
--  Pegá TODO este archivo en Supabase → SQL Editor → New query → Run.
--  Se puede volver a ejecutar sin perder datos.
-- =====================================================================

-- ---------- Tablas ----------

create table if not exists admins (
  email text primary key
);

create table if not exists productos (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  categoria    text not null default 'General',
  precio       numeric(12,2) not null default 0 check (precio >= 0),
  stock        integer not null default 0,
  stock_minimo integer not null default 5,
  emoji        text default '❄️',
  imagen       text,
  activo       boolean not null default true,
  creado       timestamptz not null default now()
);

create table if not exists pedidos (
  id             bigint generated by default as identity primary key,
  creado         timestamptz not null default now(),
  estado         text not null default 'nuevo'
                 check (estado in ('nuevo','preparando','enviado','entregado','cancelado')),
  nombre         text not null,
  telefono       text not null default '',  -- opcional: la tienda ya no lo pide
  entrega        text not null default 'envio' check (entrega in ('envio','retiro')),
  direccion      text,
  localidad      text,
  fecha_entrega  date,
  horario        text,
  pago           text,
  observaciones  text,
  total          numeric(12,2) not null default 0,
  nota_interna   text
);

create table if not exists pedido_items (
  id          bigint generated by default as identity primary key,
  pedido_id   bigint not null references pedidos(id) on delete cascade,
  producto_id bigint references productos(id) on delete set null,
  nombre      text not null,
  precio      numeric(12,2) not null,
  cantidad    integer not null check (cantidad > 0)
);

-- Historial de todos los movimientos de stock (ventas, ingresos, ajustes)
create table if not exists movimientos_stock (
  id          bigint generated by default as identity primary key,
  fecha       timestamptz not null default now(),
  producto_id bigint not null references productos(id) on delete cascade,
  cantidad    integer not null,          -- positivo = entra, negativo = sale
  stock_final integer not null,
  motivo      text not null,             -- 'venta', 'cancelación', 'ingreso', 'ajuste', ...
  pedido_id   bigint references pedidos(id) on delete set null,
  usuario     text
);

create index if not exists pedidos_creado_idx on pedidos (creado desc);
create index if not exists pedidos_telefono_idx on pedidos (telefono);
create index if not exists items_pedido_idx on pedido_items (pedido_id);
create index if not exists mov_producto_idx on movimientos_stock (producto_id, fecha desc);

-- Nadie accede a las tablas directamente: todo pasa por las funciones de abajo.
alter table admins            enable row level security;
alter table productos         enable row level security;
alter table pedidos           enable row level security;
alter table pedido_items      enable row level security;
alter table movimientos_stock enable row level security;

-- ---------- Funciones internas ----------

create or replace function es_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from admins where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function exigir_admin() returns void
language plpgsql stable security definer set search_path = public as $$
begin
  if not es_admin() then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
end $$;

create or replace function mover_stock(p_producto bigint, p_cantidad integer, p_motivo text, p_pedido bigint default null)
returns integer
language plpgsql security definer set search_path = public as $$
declare v_stock integer;
begin
  update productos set stock = stock + p_cantidad where id = p_producto returning stock into v_stock;
  if v_stock is null then
    raise exception 'Producto inexistente';
  end if;
  insert into movimientos_stock (producto_id, cantidad, stock_final, motivo, pedido_id, usuario)
  values (p_producto, p_cantidad, v_stock, p_motivo, p_pedido, auth.jwt() ->> 'email');
  return v_stock;
end $$;

-- Identifica a un cliente: por teléfono si lo tiene, si no por nombre
create or replace function clave_cliente(p_telefono text, p_nombre text) returns text
language sql immutable set search_path = public as $$
  select coalesce(nullif(trim(p_telefono), ''), 'nombre:' || lower(trim(p_nombre)));
$$;

create or replace function pedido_json(p_id bigint) returns jsonb
language sql stable security definer set search_path = public as $$
  select to_jsonb(p) || jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
               'producto_id', i.producto_id, 'nombre', i.nombre,
               'precio', i.precio, 'cantidad', i.cantidad) order by i.id)
      from pedido_items i where i.pedido_id = p.id), '[]'::jsonb))
  from pedidos p where p.id = p_id;
$$;

-- ---------- Funciones públicas (tienda) ----------

create or replace function catalogo() returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', id, 'nombre', nombre, 'categoria', categoria, 'precio', precio,
           'stock', greatest(stock, 0), 'emoji', emoji, 'imagen', imagen)
         order by categoria, nombre), '[]'::jsonb)
  from productos where activo;
$$;

-- p_cliente: {nombre, telefono, entrega, direccion, localidad, fecha_entrega, horario, pago, observaciones}
-- p_items:   [{producto_id, cantidad}, ...]
create or replace function crear_pedido(p_cliente jsonb, p_items jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id    bigint;
  v_total numeric(12,2) := 0;
  v_item  record;
  v_prod  productos%rowtype;
  v_faltan text[] := '{}';
begin
  if coalesce(trim(p_cliente ->> 'nombre'), '') = '' or coalesce(trim(p_cliente ->> 'direccion'), '') = '' then
    raise exception 'Faltan nombre o dirección';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido está vacío';
  end if;
  if jsonb_array_length(p_items) > 100 then
    raise exception 'Demasiados productos en un pedido';
  end if;

  -- 1) Se verifica el stock antes de crear el pedido (así no se "gastan" números de pedido).
  --    Los productos se bloquean en orden para que dos clientes no compren el mismo stock a la vez.
  for v_item in
    select (e ->> 'producto_id')::bigint as producto_id, sum((e ->> 'cantidad')::int)::int as cantidad
    from jsonb_array_elements(p_items) e
    group by 1 order by 1
  loop
    if v_item.cantidad is null or v_item.cantidad <= 0 or v_item.cantidad > 1000 then
      raise exception 'Cantidad inválida';
    end if;
    select * into v_prod from productos where id = v_item.producto_id and activo for update;
    if not found then
      raise exception 'Hay un producto que ya no está disponible. Actualizá la página.';
    end if;
    if v_prod.stock < v_item.cantidad then
      v_faltan := v_faltan || format('%s (quedan %s)', v_prod.nombre, greatest(v_prod.stock, 0));
    end if;
  end loop;

  if array_length(v_faltan, 1) > 0 then
    raise exception 'Sin stock suficiente: %', array_to_string(v_faltan, ', ');
  end if;

  -- 2) Se crea el pedido y se descuenta el stock (con los precios de la base, no los del navegador)
  insert into pedidos (nombre, telefono, entrega, direccion, localidad, fecha_entrega, horario, pago, observaciones)
  values (
    left(trim(p_cliente ->> 'nombre'), 120),
    coalesce(left(trim(p_cliente ->> 'telefono'), 40), ''),
    case when p_cliente ->> 'entrega' = 'retiro' then 'retiro' else 'envio' end,
    left(p_cliente ->> 'direccion', 200),
    left(p_cliente ->> 'localidad', 100),
    nullif(p_cliente ->> 'fecha_entrega', '')::date,
    left(p_cliente ->> 'horario', 60),
    left(p_cliente ->> 'pago', 60),
    left(p_cliente ->> 'observaciones', 500)
  ) returning id into v_id;

  for v_item in
    select (e ->> 'producto_id')::bigint as producto_id, sum((e ->> 'cantidad')::int)::int as cantidad
    from jsonb_array_elements(p_items) e
    group by 1 order by 1
  loop
    select * into v_prod from productos where id = v_item.producto_id;
    insert into pedido_items (pedido_id, producto_id, nombre, precio, cantidad)
    values (v_id, v_prod.id, v_prod.nombre, v_prod.precio, v_item.cantidad);
    perform mover_stock(v_prod.id, -v_item.cantidad, 'venta', v_id);
    v_total := v_total + v_prod.precio * v_item.cantidad;
  end loop;

  update pedidos set total = v_total where id = v_id;
  return pedido_json(v_id);
end $$;

-- ---------- Funciones del panel (sólo administradores) ----------

create or replace function admin_pedidos(
  p_desde date default null, p_hasta date default null,
  p_estado text default null, p_buscar text default null, p_telefono text default null)
returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform exigir_admin();
  return coalesce((
    select jsonb_agg(pedido_json(p.id) order by p.creado desc)
    from pedidos p
    where (p_desde is null or (p.creado at time zone 'America/Argentina/Buenos_Aires')::date >= p_desde)
      and (p_hasta is null or (p.creado at time zone 'America/Argentina/Buenos_Aires')::date <= p_hasta)
      and (coalesce(p_estado, '') = '' or p.estado = p_estado
           or (p_estado = 'pendientes' and p.estado in ('nuevo','preparando','enviado')))
      and (coalesce(p_telefono, '') = '' or clave_cliente(p.telefono, p.nombre) = p_telefono)
      and (coalesce(p_buscar, '') = ''
           or p.nombre ilike '%' || p_buscar || '%'
           or p.telefono ilike '%' || p_buscar || '%'
           or p.direccion ilike '%' || p_buscar || '%'
           or p.id::text = ltrim(p_buscar, '#0'))
    limit 500), '[]'::jsonb);
end $$;

create or replace function admin_pedido(p_id bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform exigir_admin();
  return pedido_json(p_id);
end $$;

-- Cambia el estado. Si se cancela, el stock vuelve; si se reactiva, se descuenta de nuevo.
create or replace function admin_cambiar_estado(p_id bigint, p_estado text, p_nota text default null)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_ant  text;
  v_item record;
  v_stock integer;
begin
  perform exigir_admin();
  select estado into v_ant from pedidos where id = p_id for update;
  if v_ant is null then raise exception 'Pedido inexistente'; end if;

  if p_estado = 'cancelado' and v_ant <> 'cancelado' then
    for v_item in select * from pedido_items where pedido_id = p_id and producto_id is not null order by producto_id loop
      perform mover_stock(v_item.producto_id, v_item.cantidad, 'cancelación', p_id);
    end loop;
  elsif v_ant = 'cancelado' and p_estado <> 'cancelado' then
    for v_item in select * from pedido_items where pedido_id = p_id and producto_id is not null order by producto_id loop
      select stock into v_stock from productos where id = v_item.producto_id for update;
      if v_stock < v_item.cantidad then
        raise exception 'No hay stock para reactivar: % (quedan %)', v_item.nombre, v_stock;
      end if;
      perform mover_stock(v_item.producto_id, -v_item.cantidad, 'venta (reactivado)', p_id);
    end loop;
  end if;

  update pedidos set estado = p_estado, nota_interna = coalesce(p_nota, nota_interna) where id = p_id;
  return pedido_json(p_id);
end $$;

create or replace function admin_productos() returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform exigir_admin();
  return coalesce((select jsonb_agg(to_jsonb(p) order by p.categoria, p.nombre) from productos p), '[]'::jsonb);
end $$;

-- Crea (sin id) o modifica (con id) un producto. El stock NO se toca acá: se usa admin_mover_stock.
create or replace function admin_guardar_producto(p jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_id bigint := nullif(p ->> 'id', '')::bigint;
begin
  perform exigir_admin();
  if coalesce(trim(p ->> 'nombre'), '') = '' then raise exception 'Falta el nombre'; end if;
  if v_id is null then
    insert into productos (nombre, categoria, precio, stock_minimo, emoji, imagen, activo)
    values (trim(p ->> 'nombre'), coalesce(nullif(trim(p ->> 'categoria'), ''), 'General'),
            coalesce((p ->> 'precio')::numeric, 0), coalesce((p ->> 'stock_minimo')::int, 5),
            nullif(p ->> 'emoji', ''), nullif(p ->> 'imagen', ''), coalesce((p ->> 'activo')::boolean, true))
    returning id into v_id;
    if coalesce((p ->> 'stock')::int, 0) <> 0 then
      perform mover_stock(v_id, (p ->> 'stock')::int, 'stock inicial');
    end if;
  else
    update productos set
      nombre       = trim(p ->> 'nombre'),
      categoria    = coalesce(nullif(trim(p ->> 'categoria'), ''), 'General'),
      precio       = coalesce((p ->> 'precio')::numeric, precio),
      stock_minimo = coalesce((p ->> 'stock_minimo')::int, stock_minimo),
      emoji        = nullif(p ->> 'emoji', ''),
      imagen       = nullif(p ->> 'imagen', ''),
      activo       = coalesce((p ->> 'activo')::boolean, activo)
    where id = v_id;
  end if;
  return (select to_jsonb(x) from productos x where id = v_id);
end $$;

-- Ingreso de mercadería (cantidad positiva) o ajuste/merma (negativa)
create or replace function admin_mover_stock(p_producto bigint, p_cantidad integer, p_motivo text)
returns integer
language plpgsql security definer set search_path = public as $$
begin
  perform exigir_admin();
  if p_cantidad = 0 then raise exception 'La cantidad no puede ser 0'; end if;
  return mover_stock(p_producto, p_cantidad, coalesce(nullif(trim(p_motivo), ''), 'ajuste'));
end $$;

create or replace function admin_movimientos(p_producto bigint default null) returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform exigir_admin();
  return coalesce((
    select jsonb_agg(to_jsonb(m) || jsonb_build_object('producto', pr.nombre) order by m.fecha desc)
    from (select * from movimientos_stock
          where p_producto is null or producto_id = p_producto
          order by fecha desc limit 300) m
    join productos pr on pr.id = m.producto_id), '[]'::jsonb);
end $$;

-- Clientes: se agrupan por teléfono (o por nombre, si el pedido no tiene teléfono)
create or replace function admin_clientes(p_buscar text default null) returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform exigir_admin();
  return coalesce((
    select jsonb_agg(c order by c.ultimo desc) from (
      select clave_cliente(telefono, nombre) as clave,
             max(telefono) as telefono,
             (array_agg(nombre order by creado desc))[1]    as nombre,
             (array_agg(direccion order by creado desc) filter (where entrega = 'envio'))[1] as direccion,
             (array_agg(localidad order by creado desc) filter (where entrega = 'envio'))[1] as localidad,
             count(*) filter (where estado <> 'cancelado') as pedidos,
             coalesce(sum(total) filter (where estado <> 'cancelado'), 0) as gastado,
             max(creado) as ultimo
      from pedidos
      group by 1
      having coalesce(p_buscar, '') = ''
          or bool_or(nombre ilike '%' || p_buscar || '%')
          or bool_or(telefono ilike '%' || p_buscar || '%')
    ) c), '[]'::jsonb);
end $$;

create or replace function admin_resumen() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_hoy date := (now() at time zone 'America/Argentina/Buenos_Aires')::date;
begin
  perform exigir_admin();
  return jsonb_build_object(
    'pedidos_hoy', (select count(*) from pedidos
                    where (creado at time zone 'America/Argentina/Buenos_Aires')::date = v_hoy and estado <> 'cancelado'),
    'ventas_hoy',  (select coalesce(sum(total), 0) from pedidos
                    where (creado at time zone 'America/Argentina/Buenos_Aires')::date = v_hoy and estado <> 'cancelado'),
    'ventas_mes',  (select coalesce(sum(total), 0) from pedidos
                    where date_trunc('month', creado at time zone 'America/Argentina/Buenos_Aires') = date_trunc('month', v_hoy::timestamp)
                      and estado <> 'cancelado'),
    'pendientes',  (select count(*) from pedidos where estado in ('nuevo','preparando','enviado')),
    'nuevos',      (select count(*) from pedidos where estado = 'nuevo'),
    'stock_bajo',  coalesce((select jsonb_agg(jsonb_build_object('id', id, 'nombre', nombre, 'stock', stock, 'stock_minimo', stock_minimo) order by stock)
                             from productos where activo and stock <= stock_minimo), '[]'::jsonb),
    'mas_vendidos', coalesce((select jsonb_agg(t) from (
                      select i.nombre, sum(i.cantidad) as cantidad, sum(i.cantidad * i.precio) as importe
                      from pedido_items i join pedidos p on p.id = i.pedido_id
                      where p.estado <> 'cancelado' and p.creado > now() - interval '30 days'
                      group by i.nombre order by 2 desc limit 5) t), '[]'::jsonb)
  );
end $$;

-- ---------- Permisos ----------
revoke all on function mover_stock(bigint, integer, text, bigint) from public, anon, authenticated;
revoke all on function pedido_json(bigint) from public, anon, authenticated;
revoke all on function exigir_admin() from public, anon, authenticated;
grant execute on function catalogo() to anon, authenticated;
grant execute on function crear_pedido(jsonb, jsonb) to anon, authenticated;
grant execute on function es_admin() to authenticated;

-- ---------- Productos de ejemplo (sólo si la tabla está vacía) ----------
do $$
declare r record;
begin
  if not exists (select 1 from productos) then
    for r in select * from (values
      ('Empanadas de carne x12',      'Empanadas',    9000, 30, '🥟'),
      ('Empanadas jamón y queso x12', 'Empanadas',    8500, 30, '🥟'),
      ('Empanadas de pollo x12',      'Empanadas',    8800, 30, '🥟'),
      ('Milanesas de carne x1 kg',    'Milanesas',   12000, 20, '🥩'),
      ('Milanesas de pollo x1 kg',    'Milanesas',   10500, 20, '🍗'),
      ('Milanesas de soja x6',        'Milanesas',    5500, 15, '🌱'),
      ('Hamburguesas caseras x4',     'Hamburguesas', 6000, 25, '🍔'),
      ('Pizza muzzarella',            'Pizzas',       7000, 10, '🍕'),
      ('Prepizzas x2',                'Pizzas',       3000, 10, '🍕'),
      ('Papas fritas x2,5 kg',        'Vegetales',    7500, 12, '🍟'),
      ('Mix de verduras x1 kg',       'Vegetales',    4000, 12, '🥦'),
      ('Nuggets de pollo x1 kg',      'Rebozados',    9500, 15, '🍗')
    ) v(nombre, categoria, precio, stock, emoji) loop
      insert into productos (nombre, categoria, precio, emoji) values (r.nombre, r.categoria, r.precio, r.emoji);
      perform mover_stock(currval(pg_get_serial_sequence('productos', 'id')), r.stock, 'stock inicial');
    end loop;
  end if;
end $$;

-- =====================================================================
--  ÚLTIMO PASO: poné tu email (el mismo con el que creaste el usuario
--  en Authentication → Users) y ejecutá esta línea:
--
--  insert into admins (email) values ('tu-email@ejemplo.com') on conflict do nothing;
-- =====================================================================
